name: Test package

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - "**"
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"
jobs:
  check-code:
    # This skips running the test if '[ci skip]' or '[skip ci]' is in the commit message
    # if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"

    # Choose which operating system to run on, for more options see:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-22.04

    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: "Install code"
        run: pip install .[test,docs]

      - name: Flake8 code
        run: flake8 .

      - name: Mypy check
        run: |
           pip install mypy
           python -m mypy . --exclude=build

      - name: Generate coverage report
        run: python -m pytest --cov=mypackage test

      - name: Generate html report
        run: python -m coverage html
           
      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov
          if-no-files-found: error

  test-code:
    # This code depends on the result of check-code
    needs: check-code
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-12]    
    
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - uses: actions/checkout@v3
    
      - name: "Install mypackage"
        run: pip install .[test]

      - name: Run tests
        run: |
          python -m pytest test/